### PR TITLE
use sh instead of bash for cmake unittests

### PR DESCRIPTION
**Pull request by ClaytonCalabrese**
> No need to use bash for this, sh will suffice. Makes this work on distros that don't ship with bash installed by default (Alpine), and bash's days may be numbered on macos anyways.

### CODE REVIEW

**Comment by ClaytonCalabrese** [comment]
Resolves https://github.com/eosnetworkfoundation/mandel/issues/367

**Review by heifner — APPROVED** [review]

**Comment by ClaytonCalabrese** [comment]
Resolves https://github.com/eosnetworkfoundation/mandel/issues/356

**Comment by jgiszczak** [comment]
`bash` is invoked by Cluster.py to run `bios_boot.sh`.  It's used by eosio-launcher in its main.cpp for the same reason.  It's also the explicit shell used for each of:

- `tests/p2p_tests/dawn_515/test.sh`
- 'tests/db_modes_test.sh`
- 'tests/full-version-label.sh`

**Review by jgiszczak — CHANGES_REQUESTED** [review]
`bash` is invoked by Cluster.py to run `bios_boot.sh`.  It's used by eosio-launcher in its main.cpp for the same reason.  It's also the explicit shell used for each of:

- `tests/p2p_tests/dawn_515/test.sh`
- 'tests/db_modes_test.sh`
- 'tests/full-version-label.sh`

**Review by heifner — APPROVED** [review]
Lets work @jgiszczak changes in a different PR.

**Review by jgiszczak — APPROVED** [review]

**Pull request merged**
