### PR TITLE
Limit input transaction dedup time

### PR DESCRIPTION
**Pull request by heifner**
- Respect the `cpu-effort-percent` while removing expired transactions from deduplication list.

### CODE REVIEW

**Comment by swatanabe** [comment]
I'm pretty sure that extra expired `transaction_objects` do not affect consensus.  Have you fully verified this?

If the timer expires, it will result in an empty block, right?

**Comment by heifner** [comment]
Yes, an empty block if timer expires, similar to if it expires in the other steps of the producer_plugin start_block.
As for consensus, I was also a bit worried, but these are input transactions that have succeeded. Extra transactions in the list would result in a duplicate transaction exception instead of an expired transaction. Since either would only be during building of a block it should not affect consensus.

**Review by swatanabe — APPROVED** [review]
Also, just to confirm, this is not a backport of changes to EOSIO and there is no conversation elsewhere that needs to be referenced?

**Comment by heifner** [comment]
This is not a backport, although EOSIO/eos could certainly use this change. I should push it up there as well.
The conversation was with Wax BPs on telegram.

**Comment by heifner** [comment]
A bit of more info about this. WAX was seeing BPs taking more than `cpu-effort-percent` time in removing duplicate transactions. Upgrading to EOSIO/eos 2.1.x with your improved chainbase fixed the problem for them. Since Mandel also has the newer chainbase presumably that would also fix their issue.

**Comment by heifner** [comment]
https://github.com/EOSIO/eos/pull/11071

**Pull request merged**
