### PR TITLE
[3.2] Separate out signature provider from producer plugin

### LINKED ISSUE #540: Backport: separate out signature provider from producer plugin
https://github.com/EOSIO/eos/pull/9066

### PR DESCRIPTION
**Pull request by heifner**
Currently the only time nodeos needs to perform a signature is when signing a block. Thus defining keys and where to find the private key for those keys has been in producer plugin.

Going forward though, this may not be the only use case for signing in nodeos.

Move the signature provider code out of producer plugin to its own plugin so that any plugin can leverage signing through a single impl.

Backports: https://github.com/EOSIO/eos/pull/9066 & https://github.com/EOSIO/eos/pull/9079

Resolves #540 
Resolves https://github.com/eosnetworkfoundation/mandel/issues/521

### CODE REVIEW

**Comment by spoonincode** [comment]
The only reason this was separated out in the first place was for `witness_plugin` which of course is no more. I mean I guess it doesn't hurt anything but doesn't really gain anything either; any particular reason was interested to port it?

**Comment by heifner** [comment]
> The only reason this was separated out in the first place was for `witness_plugin` which of course is no more. I mean I guess it doesn't hurt anything but doesn't really gain anything either; any particular reason was interested to port it?

Seemed like a nice separation of concerns, but I'm ok with just closing this out and not backporting.

**Comment by heifner** [comment]
> Seemed like a nice separation of concerns, but I'm ok with just closing this out and not backporting.

@larryk85 @arhag opinions?

**Review by spoonincode — APPROVED** [review]

**Comment by larryk85** [comment]
> > Seemed like a nice separation of concerns, but I'm ok with just closing this out and not backporting.
> 
> @larryk85 @arhag opinions?

I agree it does.  Only a million more spots to go to get really good separation of concerns across the project 😃.

**Review by larryk85 — APPROVED** [review]

**Pull request merged**
